# Generated by Django 5.0.2 on 2024-03-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinobiShop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(choices=[('polera', 'Polera'), ('hoodie', 'Hoodie'), ('sueter', 'Sueter'), ('pantalon', 'Pantalon'), ('gorro', 'Gorro'), ('accesorio', 'Accesorio')], default='polera', max_length=20),
        ),
    ]
